# Generated by Django 3.2.20 on 2023-08-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(default='fgfgh', upload_to='pic'),
            preserve_default=False,
        ),
    ]
